In [109]:
import pandas as pd 
from langdetect import detect
import tensorflow as tf
import transformers
from transformers import BertConfig, AutoTokenizer, TFBertModel, BertTokenizer, TFBertForSequenceClassification, BertModel
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import hamming_loss
from utils.registry import load_model
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import pad_sequences
from utils.data_preproc import cleaning_text
import joblib

In [110]:
! tree


.
├── generate_tweet_iris.ipynb
├── haha.txt
├── __init__.py
├── Iris_2.ipynb
├── iris_3-Copy1.ipynb
├── iris_3.ipynb
├── iris_4.ipynb
├── Iris Notebook.ipynb
├── iris_streamlit.ipynb
├── irisv5.ipynb
├── LSTM_DL.ipynb
├── Marianne.ipynb
├── Mariannev2.ipynb
├── Mariannev2.ipynb:Zone.Identifier
├── Mariannev3.ipynb
├── __pycache__
│   └── __init__.cpython-310.pyc
├── test-bert.ipynb
└── test_lua.ipynb

1 directory, 18 files


In [111]:
data=pd.read_csv('../data/labelling_dataset_v1.csv')

In [112]:
data.head()

text  racism  religion  \
0  Yes indeed. She sort of reminds me of the elde...       1         0   
1  The trans women reading this tweet right now i...       0         0   
2  Question: These 4 broads who criticize America...       0         0   
3  It is about time for all illegals to go back t...       0         0   
4  For starters bend over the one in pink and kic...       0         0   

   xenophobia  misogyny  transphobia  homophobia  \
0           0         0            0           0   
1           0         0            1           0   
2           1         0            0           0   
3           1         0            0           0   
4           0         1            0           0   

                                      text_processed  
0  yes indeed she sort of remind me of the elder ...  
1  the trans women read this tweet right now be b...  
2  question these broads who criticize america wh...  
3  it be about time for all illegals to go back t...  
4  for starters bend over the one in pink and kic...

In [122]:
model = load_model('../GRU_classif')

In [123]:
model.weights

[<tf.Variable 'embedding/embeddings:0' shape=(39174, 50) dtype=float32, numpy=
 array([[-0.00197392, -0.04950519,  0.02095826, ...,  0.02697733,
          0.0347213 ,  0.02741968],
        [-0.07434124, -0.06303854, -0.02192898, ...,  0.02178095,
          0.00758335,  0.0263961 ],
        [ 0.03205993, -0.04147709,  0.03960084, ..., -0.05897377,
          0.03714954, -0.05896284],
        ...,
        [ 0.004668  , -0.04208574, -0.038828  , ..., -0.00510353,
         -0.00246674, -0.00635874],
        [ 0.04527494,  0.03923582,  0.03357867, ...,  0.00486529,
         -0.04217653,  0.01994053],
        [ 0.00233836, -0.0066291 , -0.04963028, ...,  0.04997966,
         -0.02780968, -0.03874063]], dtype=float32)>,
 <tf.Variable 'gru/gru_cell/kernel:0' shape=(50, 60) dtype=float32, numpy=
 array([[ 0.30962777,  0.07257307, -0.05396277, ...,  0.13521294,
         -0.07545161,  0.00748688],
        [ 0.08107282, -0.03717114,  0.02668694, ...,  0.10987555,
         -0.04112379,  0.06729835],

In [124]:
data_processed=pd.read_csv('../data/labelling_dataset_v1.csv')

# Split into training and testing data
X = data_processed["text_processed"]
y = data_processed.drop(labels=["text_processed", "text"], axis=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=3)

### Let's tokenize the vocabulary
tk = Tokenizer()
tk.fit_on_texts(X_train)
vocab_size = len(tk.word_index)

# We apply the tokenization to the train and test set
X_train_token = tk.texts_to_sequences(X_train)
X_test_token = tk.texts_to_sequences(X_test)

X_train_pad = pad_sequences(X_train_token, dtype='float32', padding='post', maxlen = 180)
X_test_pad = pad_sequences(X_test_token, dtype='float32', padding='post', maxlen = 180)

In [125]:
y_pred = model.predict(X_train_pad)

1325/1325 [==============================] - 37s 27ms/step


In [137]:
tweet = "Muslim people out of France"

In [138]:
data = pd.DataFrame({"text":[tweet]})
data["text"] = data["text"].apply(cleaning_text)

#tokenizer_bert
X_pred=data["text"]
tk = joblib.load("../tokenizer.joblib")
X_pred_tok = tk.texts_to_sequences(X_pred)
X_pred_pad = pad_sequences(X_pred_tok, dtype='float32', padding='post', maxlen = 180)
y_pred = model.predict(X_pred_pad)

probabilities = np.array(y_pred)
df=pd.DataFrame(probabilities, columns=['Racist tweet','Religious Hate','Xenophobia','Misogyny','Transphobia','Homophobia'])
print(probabilities)
label = df.idxmax(axis=1).iloc[0]

print(label)

1/1 [==============================] - 0s 37ms/step
[[4.6679188e-02 9.0563917e-01 3.6635421e-02 1.4836957e-04 4.0254677e-03
  6.8724733e-03]]
Religious Hate


In [139]:
[[0.28474218 0.10841988 0.16050139 0.20107783 0.11093782 0.13432086]]

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2040346411.py, line 1)

In [ ]:
y_pred

In [ ]:
y_pred

In [ ]:
X_pred_pad

In [ ]:
model_2 = load_model('../CNN_classifv2')